### PR TITLE
removed the redundant babel-polyfill as it causes issues with aurelia-webpack-plugin@2.0.0-rc.2

### PR DESCRIPTION
**Pull request by nashwaan**
removed the redundant babel-polyfill as it causes issues with aurelia-webpack-plugin@2.0.0-rc.2

### CODE REVIEW

**Comment by nathanchase** [comment]
@nashwaan - You don't want to remove async/await capability, which is what babel-polyfill enables. It might make sense to use [babel-plugin-transform-runtime](http://babeljs.io/docs/plugins/transform-runtime/) instead though, since it's not a polyfill but enables the regenerator runtime.

See http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await for more info.

I'll experiment locally and see if that works.

**Comment by nashwaan** [comment]
`babel-polyfill` is redundant since `aurelia-polyfills` is already loaded by `aurelia-bootstrapper` and this caused [issues on IE](https://github.com/jods4/aurelia-webpack-build/issues/33#issuecomment-293665671) when I attempted to use latest `aurelia-webpack-plugin`.

Also, I was successfully able to use `async`/`await` syntax when I use `regenerator-runtime` (without babel-polyfill):
```js
new webpack.ProvidePlugin({
    Map: 'core-js/es6/map',
    WeakMap: 'core-js/es6/weak-map',
    Promise: 'core-js/es6/promise',
    regeneratorRuntime: 'regenerator-runtime', // to support await/async syntax
}),
```

**Comment by nathanchase** [comment]
Ah, yeah - that works. I guess the `regenerator-runtime` module is already included as a dependency for something else?

**Comment by nashwaan** [comment]
Not sure, but I usually install it explicitly `npm install --save-dev regenerator-runtime`.

Thanks for merging the changes.

**Pull request merged**
